### ISSUE TITLE
error occured when pip install

### ISSUE THREAD

**Issue by zhd173** [bmoscon/orderbook#1]
occured error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/rq/kjp4msb55r5bd19srg575ssw0000gn/T/pip-install-yyluc257/order-book/CHANGES.md'
```
exec `ll` command under the dir:

```
total 40
-rw-r--r--  1 zhd  staff   5.6K Dec 28 05:31 PKG-INFO
-rw-r--r--  1 zhd  staff   3.7K Dec 28 05:26 README.md
drwxr-xr-x  6 zhd  staff   192B Jan  6 16:11 order_book.egg-info
drwxr-xr-x  5 zhd  staff   160B Jan  6 16:11 orderbook
-rw-r--r--  1 zhd  staff    38B Dec 28 05:31 setup.cfg
-rw-r--r--  1 zhd  staff   1.6K Dec 28 02:23 setup.py
```

**Comment by bmoscon** [comment]
please provide more information about how you pip installed. Here is the output from when I pip install:

 ~ pip install order-book
Collecting order-book
  Downloading order_book-0.0.2-cp38-cp38-macosx_10_9_x86_64.whl (20 kB)
Installing collected packages: order-book
Successfully installed order-book-0.0.2


So, how did you do it? From the source? Something else? Also please list OS and python versions

**Comment by zhd173** [comment]
ok

**Comment by zhd173** [comment]
It looks like the CHANGES.md file is missing

**Comment by bmoscon** [comment]
are you using the new M1 processor?

**Comment by zhd173** [comment]
> are you using the new M1 processor?

no, I'm using old mbp

**Comment by bmoscon** [comment]
I can include the changes file, but you shouldnt need it. I'm more concerned that its trying to build from source rather than just using the wheel thats been pre-built. Not sure why its doing that, I'm running big sur as well.

**Comment by zhd173** [comment]
It is not urgent，I have installed with source code. ☺️

Could it be caused by the `get_long_description()` function in steup.py?

**Comment by bmoscon** [comment]
yes, thats the cause of your immediate issue (and i fixed and verified the fix) - but again, it should just pull down the wheel and use that, not sure why its not. Going to mark this as closed/fixed since I updated the tooling to include the file
