### ISSUE TITLE
Should anyone use this?

### ISSUE THREAD

**Issue by ibmua** [bmoscon/orderbook#11]
Just so we're on the same page on what C++ vs Python speed difference is in general https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/gpp-python3.html . I would argue that 2x speedup vs http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html which is documented and, in comparison, very well developed and Pythonic is not a good choice, including in cryptofeed. I'm guessing you expected a higher performance improvement when you started developing it. But as it's only 2x I'd really recommend you go with SortedDict and abandon this. You'll either not make this properly, or will have to spend a serious amount of time to turn it from a much worse overall choice into a very slightly better one. For me personally, current cryptofeed experience is a huge downgrade from when you simply used dict that I later sorted and converted to orderedDict using a oneliner.

**Comment by bmoscon** [comment]
thank you for your opinion, you are free to use what you like

**Comment by ibmua** [comment]
Also, you may want to look into NumPy which is also written in C++ and is able to sort things fast while being well developed.

**Comment by bmoscon** [comment]
I welcome PRs

**Comment by ibmua** [comment]
This is how to do sorting via Numpy
```
import numpy
a = numpy.array([ [300.3, 0.1], [200.2, 0.2], [400.4, 0.3] ])
b = a[a[:, 0].argsort()]
print(b)
```
>>
[[2.002e+02 2.000e-01]
 [3.003e+02 1.000e-01]
 [4.004e+02 3.000e-01]]

I'm not sure it will be as fast (it's definitely not as fast as adding new rows to a C++ STL "map") and I'm not sure that this was most of the point in using it. I wasn't able to comprehend your code, I didn't understand what you were trying to solve there with C. I never wrote C extensions for Python yet. And your code seems like doubly obfuscated, cause it seems like you're not just bridging C to Python, but also Python to C? I don't know if I understand what you're even trying to do there. Like, what I would expect to see there is some STL use ("sort", maybe, "map"), but I found none of that and weren't even able to locate where sorting logic is, so maybe I just fundamentally don't understand the purpose of all that. Can't say I found any code there that looked like a good candidate for speedup via moving to C++. Looks like a bunch of if statements, maybe a lone non-nested "for" loop sometimes. Those if statements will probably take about as much time with Python and that lone for loop not much more, really. Like if you were doing sorting via C++ STL vs Python there would be a perf difference, especially for larger amounts of rows, but with that code.. Well, maybe I just didn't understand it, I donno.

**Comment by ibmua** [comment]
> Numpy won't work with Decimal in case this is important.

But it's not like you're going to be able to get anything like high performance code with Decimal


```
from decimal import Decimal
import time
import numpy as np


start = time.time()
a = np.array([1], dtype=np.longdouble)
for x in range(10 * 1000 * 1000):
	a = a + 0.00001
end = time.time()
print(f"a {a}, time { '{0:10.3f}'.format(end - start)}")

start = time.time()
a = np.array([1], dtype=np.float128)
for x in range(10 * 1000 * 1000):
	a = a + 0.00001
end = time.time()
print(f"a {a}, time { '{0:10.3f}'.format(end - start)}")

start = time.time()
a = np.array([1], dtype=np.float64)
for x in range(10 * 1000 * 1000):
	a = a + 0.00001
end = time.time()
print(f"a {a}, time { '{0:10.3f}'.format(end - start)}")

start = time.time()
a = Decimal(1)
for x in range(10 * 1000 * 1000):
	a = a + Decimal(0.00001)
end = time.time()
print(f"a {a}, time { '{0:10.3f}'.format(end - start)}")

start = time.time()
a = float(1)
for x in range(10 * 1000 * 1000):
	a = a + float(0.00001)
end = time.time()
print(f"a {a}, time { '{0:10.3f}'.format(end - start)}")
```


a [101.], time      5.911
a [101.], time      5.989
a [101.00000002], time      4.624
a 101.0000000000000081802979000, time      7.077
a 101.00000002086118, time      0.841
