### ISSUE TITLE
Methods to return data as list

### ISSUE THREAD

**Issue by bmoscon** [bmoscon/orderbook#13]
Provide following methods to export data:

1. prices() - returns list of prices for each level (would be called on .bids or .asks)
2. to_list() - like to dict, but returns a list of pairs (price, size) for each level in the side (would be called on .bids or .asks)
3. ob.to_list() - like above, but would be a dict {bids: [(price, size)..., asks: [....]}

**Comment by lijiachang** [comment]
Hi, i want to known this feature any progress?

**Comment by lijiachang** [comment]
@bmoscon  Looking forward to your reply

**Comment by bmoscon** [comment]
done
