### ISSUE TITLE
Issues installing from source

### ISSUE THREAD

**Issue by cjelsa** [bmoscon/orderbook#23]
**Describe the bug**
Errors when trying to install

**To Reproduce**
python3 setup.py install

**Expected behavior**
Installation of package

**Screenshots**
running install
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating order_book.egg-info
writing order_book.egg-info/PKG-INFO
writing dependency_links to order_book.egg-info/dependency_links.txt
writing top-level names to order_book.egg-info/top_level.txt
writing manifest file 'order_book.egg-info/SOURCES.txt'
reading manifest file 'order_book.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'order_book.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11.0-arm64/egg
running install_lib
running build_ext
building 'order_book' extension
creating build
creating build/temp.macosx-11.0-arm64-cpython-39
creating build/temp.macosx-11.0-arm64-cpython-39/orderbook
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -I/opt/homebrew/Caskroom/miniforge/base/include/python3.9 -c orderbook/orderbook.c -o build/temp.macosx-11.0-arm64-cpython-39/orderbook/orderbook.o -O3
In file included from orderbook/orderbook.c:7:
orderbook/orderbook.h:124:15: warning: incompatible function pointer types initializing 'freefunc' (aka 'void (*)(void *)') with an expression of type 'void (PyObject *)' (aka 'void (struct _object *)') [-Wincompatible-function-pointer-types]
    .m_free = order_book_free,
              ^~~~~~~~~~~~~~~
orderbook/orderbook.c:543:9: warning: incompatible pointer to integer conversion passing 'void *' to parameter of type 'long' [-Wint-conversion]
    if (EXPECT(memchr(&data[startpos], (char) 'E', *pos - startpos), 0)) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
orderbook/utils.h:13:44: note: expanded from macro 'EXPECT'
#define EXPECT(EXPR, VAL) __builtin_expect((EXPR), (VAL))
                                           ^~~~~~
orderbook/orderbook.c:562:25: warning: passing 'uint8_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
    if (EXPECT(!strncmp(&data[startpos], "0.0000", 6) || memchr(&data[startpos], (char) 'E', *pos - startpos), 0)) {
                        ^~~~~~~~~~~~~~~
orderbook/utils.h:13:45: note: expanded from macro 'EXPECT'
#define EXPECT(EXPR, VAL) __builtin_expect((EXPR), (VAL))
                                            ^~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/string.h:84:26: note: passing argument to parameter '__s1' here
int      strncmp(const char *__s1, const char *__s2, size_t __n);
                             ^
3 warnings generated.
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -I/opt/homebrew/Caskroom/miniforge/base/include/python3.9 -c orderbook/sorteddict.c -o build/temp.macosx-11.0-arm64-cpython-39/orderbook/sorteddict.o -O3
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -fPIC -O2 -isystem /opt/homebrew/Caskroom/miniforge/base/include -arch arm64 -I/opt/homebrew/Caskroom/miniforge/base/include/python3.9 -c orderbook/utils.c -o build/temp.macosx-11.0-arm64-cpython-39/orderbook/utils.o -O3
creating build/lib.macosx-11.0-arm64-cpython-39
clang -bundle -undefined dynamic_lookup -Wl,-rpath,/opt/homebrew/Caskroom/miniforge/base/lib -L/opt/homebrew/Caskroom/miniforge/base/lib -Wl,-rpath,/opt/homebrew/Caskroom/miniforge/base/lib -L/opt/homebrew/Caskroom/miniforge/base/lib build/temp.macosx-11.0-arm64-cpython-39/orderbook/orderbook.o build/temp.macosx-11.0-arm64-cpython-39/orderbook/sorteddict.o build/temp.macosx-11.0-arm64-cpython-39/orderbook/utils.o -o build/lib.macosx-11.0-arm64-cpython-39/order_book.cpython-39-darwin.so
creating build/bdist.macosx-11.0-arm64
creating build/bdist.macosx-11.0-arm64/egg
copying build/lib.macosx-11.0-arm64-cpython-39/order_book.cpython-39-darwin.so -> build/bdist.macosx-11.0-arm64/egg
creating stub loader for order_book.cpython-39-darwin.so
byte-compiling build/bdist.macosx-11.0-arm64/egg/order_book.py to order_book.cpython-39.pyc
creating build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying order_book.egg-info/PKG-INFO -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying order_book.egg-info/SOURCES.txt -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying order_book.egg-info/dependency_links.txt -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
copying order_book.egg-info/top_level.txt -> build/bdist.macosx-11.0-arm64/egg/EGG-INFO
writing build/bdist.macosx-11.0-arm64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.order_book.cpython-39: module references __file__
creating dist
creating 'dist/order_book-0.6.0-py3.9-macosx-11.0-arm64.egg' and adding 'build/bdist.macosx-11.0-arm64/egg' to it
removing 'build/bdist.macosx-11.0-arm64/egg' (and everything under it)
Processing order_book-0.6.0-py3.9-macosx-11.0-arm64.egg
creating /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/order_book-0.6.0-py3.9-macosx-11.0-arm64.egg
Extracting order_book-0.6.0-py3.9-macosx-11.0-arm64.egg to /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages
Adding order-book 0.6.0 to easy-install.pth file

Installed /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/order_book-0.6.0-py3.9-macosx-11.0-arm64.egg
Processing dependencies for order-book==0.6.0
Searching for order-book==0.6.0
Reading https://pypi.org/simple/order-book/
/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
No local packages or working download links found for order-book==0.6.0
error: Could not find suitable distribution for Requirement.parse('order-book==0.6.0')

**Operating System:**
 - macOS Monterey 12.5.1

**Orderbook Version**
0.6.0

**Python Version**
3.9 and 3.10

**Installation Method**
From source

**Comment by bmoscon** [comment]
i cannot reproduce this, i was able to run `python setup.py install` in a brand new virtualenv with out issues in python3.9 and 3.10, using a fresh clone of this repo.

**Comment by bmoscon** [comment]
(I'm also using MacOS monterey)
