### ISSUE TITLE
Installation Failure on MacBook with Apple M3 Max and macOS Sonoma 14.4.1

### ISSUE THREAD

**Issue by aceamro** [bmoscon/orderbook#27]
Describe the bug
When attempting to install the order-book package via pip on a MacBook equipped with the Apple M3 Max chip and 36GB of memory, running macOS Sonoma version 14.4.1, the installation fails during the build extension phase. The errors include incompatible function pointer types and incompatible pointer to integer conversions, indicating that the package's C extension is not compiling correctly due to type mismatches and warnings that are treated as errors in the compilation process. Notably, similar installation attempts on Intel-based MacBook computers do not produce these errors, which may point to a unique issue with the hardware or software configuration of the newer MacBook model.

To Reproduce

    Attempt to install the package using pip install order-book on a MacBook with the Apple M3 Max chip, 36GB of memory, running macOS Sonoma 14.4.1.
    The installation fails during the "Running setup.py install for order-book" phase, with detailed errors in the terminal.

No specific small code sample is applicable here as the issue occurs at the installation phase.

Expected behavior
The installation of the order-book package was expected to complete without errors, as it typically does on other hardware and operating system configurations. The build process for any C extensions should compile successfully and allow for the package installation.

Screenshots
![image](https://github.com/bmoscon/orderbook/assets/3595071/26990cb8-37a5-4c6e-9513-734735a540f1)

Operating System:

    MacBook with Apple M3 Max, 36GB, running macOS Sonoma 14.4.1

Orderbook Version

    Version 0.6.0 of order-book was attempted.

Python Version

    This issue has been observed across various Python versions, indicating that it is not specific to any particular Python release.

Installation Method

    The library was attempted to be installed via pip from PyPI. The process used the legacy 'setup.py install' method, as noted by the deprecation warning regarding the absence of 'pyproject.toml' and the suggestion to use the '--use-pep517' option.

Additional context
The installation process was successfully completed on two different Intel-based MacBook computers, suggesting that the issue may be related to the specific hardware or software environment of the MacBook with the Apple M3 Max chip and macOS Sonoma 14.4.1. This points to a potential compatibility concern that might require attention for those using the library on the latest MacBook models and macOS versions.

**Comment by bmoscon** [comment]
i resolved this in the main branch. will release an update later after more testing

**Comment by aceamro** [comment]
I've confirmed it works fine on my machine, thanks for the quick update.

**Comment by aifirstd3v** [comment]
doesn't work..Can't install on Mac

**Comment by aifirstd3v** [comment]
@bmoscon I got this error : 

```
Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 1 install, 1 update, 0 removals

  • Updating aiohttp (3.9.1 -> 3.9.3)
  • Installing order-book (0.6.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_ext
  building 'order_book' extension
  creating build
  creating build/temp.macosx-14.0-arm64-cpython-311
  creating build/temp.macosx-14.0-arm64-cpython-311/orderbook
  clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/9y/26y83xyn2g36jr_6ds7g2lnw0000gn/T/tmpi91da1hd/.venv/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c orderbook/orderbook.c -o build/temp.macosx-14.0-arm64-cpython-311/orderbook/orderbook.o -O3
  In file included from orderbook/orderbook.c:7:
  orderbook/orderbook.h:124:15: error: incompatible function pointer types initializing 'freefunc' (aka 'void (*)(void *)') with an expression of type 'void (PyObject *)' (aka 'void (struct _object *)') [-Wincompatible-function-pointer-types]
      .m_free = order_book_free,
                ^~~~~~~~~~~~~~~
  orderbook/orderbook.c:543:9: error: incompatible pointer to integer conversion passing 'void *' to parameter of type 'long' [-Wint-conversion]
      if (EXPECT(memchr(&data[startpos], (char) 'E', *pos - startpos), 0)) {
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  orderbook/utils.h:13:44: note: expanded from macro 'EXPECT'
  #define EXPECT(EXPR, VAL) __builtin_expect((EXPR), (VAL))
                                             ^~~~~~
  orderbook/orderbook.c:562:25: warning: passing 'uint8_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
      if (EXPECT(!strncmp(&data[startpos], "0.0000", 6) || memchr(&data[startpos], (char) 'E', *pos - startpos), 0)) {
                          ^~~~~~~~~~~~~~~
  orderbook/utils.h:13:45: note: expanded from macro 'EXPECT'
  #define EXPECT(EXPR, VAL) __builtin_expect((EXPR), (VAL))
                                              ^~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/string.h:84:26: note: passing argument to parameter '__s1' here
  int      strncmp(const char *__s1, const char *__s2, size_t __n);
                               ^
  1 warning and 2 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1
  

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with order-book (0.6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "order-book (==0.6.0)"'.
```

**Comment by bmoscon** [comment]
@aifirstd3v you have to pull the repo and manually build it. I havent released the wheel / code yet, but I will do so later this week. I just resolved the last 2 warnings that I was getting so you shouldnt have any issues building now
