### ISSUE TITLE
Implementation Performance

### ISSUE THREAD

**Issue by djdjoko** [bmoscon/orderbook#3]
How does the implementation differ in from:
https://github.com/Crypto-toolbox/HFT-Orderbook

Does it also have following performance characteristics?

Add – O(log M) for the first order at a limit, O(1) for all others
Cancel – O(1)
Execute – O(1)
GetBestBid/Offer – O(1)

**Comment by bmoscon** [comment]
without looking at that code, based on what you listed here, that seems to be an orderbook for a matching engine, so its something 100% different. this is for maintaining a book from delta updates from an exchange

**Comment by djdjoko** [comment]
Understood. thank you
