### ISSUE TITLE
Errors while creating many OrderBook instances

### ISSUE THREAD

**Issue by stopdesign** [bmoscon/orderbook#4]
**Describe the bug**
I got an error when I tried to create multiple OrderBook instances or to initialise it multiple times.

```
>>> from order_book import OrderBook
>>> for n in range(1000): OrderBook().asks = {}
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: attribute name must be string, not 'order_book.OrderBook'
```

```
>>> from order_book import OrderBook
>>> a = OrderBook()
>>> for n in range(1000): a.asks = {}
...
Fatal Python error: deletion of interned string failed
Python runtime state: initialized
[1]    39663 segmentation fault  python
```

**Operating System:**
macOS 10.15.2
Ubuntu 16.04.7 LTS

**Orderbook Version**
order-book==0.2.0 installed with pip

**Python Version**
Python 3.8.6 (default, Oct 27 2020, 08:57:44)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin

order_book-0.2.0-cp38-cp38-manylinux2010_x86_64.whl
Python 3.8.8 (default, Feb 20 2021, 21:11:43)
[GCC 5.4.0 20160609] on linux

**Comment by bmoscon** [comment]
I dont disagree that is a bug, but you are not creating multiple instances, you have one instance and you're resetting the ask side many times. I'll take a look later today

**Comment by stopdesign** [comment]
Sorry for the misleading title. My initial goal was to create multiple instances of OrderBook to track many markets. Then I removed some code to have a small example with the same error.

**Comment by bmoscon** [comment]
yes, both examples "work" with only 1 call:

```python
 OrderBook().asks = {}
```

and 

```python
ob.asks = {}
```

If you call it a few times it fails. I'm thinking there is an issue with how the old dict is being deallocated, I'll have a look

**Comment by bmoscon** [comment]
fixed. There was indeed a deallocation error. Thanks for posting this, it made it a lot easier to find!
