### ISSUE TITLE
Build on windows fails

### ISSUE THREAD

**Issue by fruitschaal** [bmoscon/orderbook#5]
**Describe the bug**
Cannot install on windows machine (tried 2 different windows server versions).

When trying to install the following error occurs (same with pip install):

>python setup.py install
running install
running bdist_egg
running egg_info
writing order_book.egg-info\PKG-INFO
writing dependency_links to order_book.egg-info\dependency_links.txt
writing top-level names to order_book.egg-info\top_level.txt
reading manifest file 'order_book.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 1: path 'orderbook/' cannot end with
'/'

writing manifest file 'order_book.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_ext
building 'order_book' extension
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.2
8.29910\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Ad
ministrator\AppData\Local\Programs\Python\Python38-32\include -IC:\Users\Adminis
trator\AppData\Local\Programs\Python\Python38-32\include "-IC:\Program Files (x8
6)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\inclu
de" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MS
VC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.1
9041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shar
ed" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Pro
gram Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files
 (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcorderbook\orderbook.c /
Fobuild\temp.win32-3.8\Release\orderbook\orderbook.obj -O3
cl : Command line warning D9002 : ignoring unknown option '-O3'
orderbook.c
orderbook\orderbook.c(107): warning C4013: '__builtin_expect' undefined; assumin
g extern returning int
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.2
8.29910\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Ad
ministrator\AppData\Local\Programs\Python\Python38-32\include -IC:\Users\Adminis
trator\AppData\Local\Programs\Python\Python38-32\include "-IC:\Program Files (x8
6)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\inclu
de" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MS
VC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.1
9041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shar
ed" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Pro
gram Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files
 (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcorderbook\sorteddict.c
/Fobuild\temp.win32-3.8\Release\orderbook\sorteddict.obj -O3
cl : Command line warning D9002 : ignoring unknown option '-O3'
sorteddict.c
orderbook\sorteddict.c(163): warning C4013: '__builtin_expect' undefined; assumi
ng extern returning int
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.2
8.29910\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Ad
ministrator\AppData\Local\Programs\Python\Python38-32\include -IC:\Users\Adminis
trator\AppData\Local\Programs\Python\Python38-32\include "-IC:\Program Files (x8
6)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\inclu
de" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MS
VC\14.28.29910\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.1
9041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shar
ed" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Pro
gram Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files
 (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /Tcorderbook\utils.c /Fobu
ild\temp.win32-3.8\Release\orderbook\utils.obj -O3
cl : Command line warning D9002 : ignoring unknown option '-O3'
utils.c
creating C:\Users\Administrator\Downloads\orderbook\build\lib.win32-3.8
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.2
8.29910\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EM
BED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\
Python\Python38-32\libs /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\P
ython\Python38-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visua
l Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x86" "/LIBPATH:C:\P
rogram Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29
910\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\u
crt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x8
6" /EXPORT:PyInit_order_book build\temp.win32-3.8\Release\orderbook\orderbook.ob
j build\temp.win32-3.8\Release\orderbook\sorteddict.obj build\temp.win32-3.8\Rel
ease\orderbook\utils.obj /OUT:build\lib.win32-3.8\order_book.cp38-win32.pyd /IMP
LIB:build\temp.win32-3.8\Release\orderbook\order_book.cp38-win32.lib
   Creating library build\temp.win32-3.8\Release\orderbook\order_book.cp38-win32
.lib and object build\temp.win32-3.8\Release\orderbook\order_book.cp38-win32.exp

orderbook.obj : error LNK2001: unresolved external symbol ___builtin_expect
build\lib.win32-3.8\order_book.cp38-win32.pyd : fatal error LNK1120: 1 unresolve
d externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Communit
y\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x86\\link.exe' failed with exit s
tatus 1120

**Comment by bmoscon** [comment]
I've updated the classifiers to its clear this is only supported on linux and macos. It may compile on windows, but you'd need to use gcc or clang or other compilers that support the various directives that this uses.
