### ISSUE TITLE
SortedDict has an unexpected behaviour after interrupted for-loops

### ISSUE THREAD

**Issue by stopdesign** [bmoscon/orderbook#7]
An interrupted for-loop results in an incorrect list representation of SortedDict and an incomplete for-loop following.

```
from order_book import OrderBook

ob = OrderBook()
ob.bids = {1: 0, 2: 0}

for ob_price in ob.bids:
    break

print(len(list(ob.bids)))  # 1 // expected 2
print(len(ob.bids))        # 2
```

```
from order_book import OrderBook

ob = OrderBook()
ob.bids = {1: 0, 2: 0}

for ob_price in ob.bids:
    break

print(list(ob.bids))         # [1] // expected [2, 1]
print(ob.bids.to_dict())     # {2: 0, 1: 0}
```

```
from order_book import OrderBook

ob = OrderBook()
ob.bids = {1: 0, 2: 0}

for ob_price in ob.bids:
    break

for ob_price in ob.bids:
    print("new loop:", ob_price)  # only one iteration // expected 2
```

**Operating System:**
macOS 10.15.7

**Orderbook Version**
order-book==0.3.0 installed with pip

**Python Version**
Python 3.9.5 (default, May  4 2021, 03:33:11)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin

**Comment by stopdesign** [comment]
Now I see that `bids` (SortedDict) is an iterator, so it has this behaviour by design. But is was not obvious from the docs or the interface. It might be worth mentioning this in the docs/examples.

**Comment by bmoscon** [comment]
@stopdesign - yes thats correct. The documentation could probably use some work, thanks for opening this.

**Comment by bmoscon** [comment]
updated the readme
